[Settings]
FORCE_MODE = false
FORCE_MODE_SERIAL = 127.0.0.1:16384

[BatchFiles]
; 在此处添加需要批量处理的 JSON 文件路径，即alas/config路径下的配置文件
; 格式：每行一个文件路径，可以是绝对路径或相对路径
Files = example.json
        D:\Afterprogram\AzurLaneAutoScript\config\alas1.json
	D:\Afterprogram\AzurLaneAutoScript\config\alas2.json

[PresetSerials]
; 在此处添加常用的 Serial 值，方便快速选择，任务组里python ./change_serial/change_serial_force.py -b -p 2 -y这里的“2”表示下面第二个serial
Serials = emulator-5554
          127.0.0.1:16384
