[Settings]
FORCE_MODE = false
FORCE_MODE_SERIAL = 127.0.0.1:16384

[BatchFiles]
; 在此处添加需要批量处理的 JSON 文件路径
; 格式：每行一个文件路径，可以是绝对路径或相对路径
Files = example.json
        D:\学习\SelfProject\OCRclick\OCR_AutoClick\change_serial\example copy 2.json
        example copy 3.json

[PresetSerials]
; 在此处添加常用的 Serial 值，方便快速选择
Serials = R5CW7017LDM
          127.0.0.1:16384